Imports Microsoft.VisualBasic
Imports System
Imports System.Windows
Imports System.Windows.Controls
Imports System.Windows.Media
Imports DevExpress.AgDataGrid

Namespace AgDataGrid_FocusedColumnHeaderStyle
	Partial Public Class MainPage
		Inherits UserControl
		Public Sub New()
			InitializeComponent()
			grid.DataSource = ProductList.GetData()
		End Sub

		Private Sub grid_FocusedColumnChanged(ByVal sender As Object, ByVal e As DevExpress.AgDataGrid.FocusedColumnChangedEventArgs)
			If e.PrevFocusedColumn.HeaderStyle IsNot Nothing Then
				e.PrevFocusedColumn.HeaderStyle = New Style() With {.TargetType = GetType(AgDataGridColumnHeader)}
			End If
			e.FocusedColumn.HeaderStyle = CreateCustomStyle()
		End Sub

		Private Sub grid_ColumnsAutoGenerated(ByVal sender As Object, ByVal e As EventArgs)
			grid.Columns(0).HeaderStyle = CreateCustomStyle()
		End Sub

		Private Function CreateCustomStyle() As Style
			Dim style As New Style() With {.TargetType = GetType(AgDataGridColumnHeader)}
			style.Setters.Add(New Setter(ForegroundProperty, New SolidColorBrush(Colors.Red)))
			style.Setters.Add(New Setter(BackgroundProperty, New SolidColorBrush(Colors.Black)))
			Return style
		End Function
	End Class
End Namespace
