using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using DevExpress.AgDataGrid;

namespace AgDataGrid_FocusedColumnHeaderStyle {
    public partial class MainPage : UserControl {
        public MainPage() {
            InitializeComponent();
            grid.DataSource = ProductList.GetData();
        }

        private void grid_FocusedColumnChanged(object sender, DevExpress.AgDataGrid.FocusedColumnChangedEventArgs e) {
            if (e.PrevFocusedColumn.HeaderStyle != null) {
                e.PrevFocusedColumn.HeaderStyle = new Style() { TargetType = typeof(AgDataGridColumnHeader) };
            }
            e.FocusedColumn.HeaderStyle = CreateCustomStyle();
        }

        private void grid_ColumnsAutoGenerated(object sender, EventArgs e) {
            grid.Columns[0].HeaderStyle = CreateCustomStyle();
        }

        private Style CreateCustomStyle() {
            Style style = new Style() { TargetType = typeof(AgDataGridColumnHeader) };
            style.Setters.Add(new Setter(ForegroundProperty, new SolidColorBrush(Colors.Red)));
            style.Setters.Add(new Setter(BackgroundProperty, new SolidColorBrush(Colors.Black)));
            return style;
        }
    }
}
